### ISSUE TITLE
How can the CLIP model from OpenAI, which is in English, also support Chinese at the same time?

### ISSUE THREAD

**Issue by guanfuchen** [greyovo/PicQuery#20]
How can the CLIP model from OpenAI, which is in English, also support Chinese at the same time?

**Comment by ersanliqiao** [comment]
translate from chinese

**Comment by greyovo** [comment]
I used the translation feature in Google's MLKit to convert Chinese input to English. In order to be able to use it offline, I embedded the downloaded translation model directly into the asset and copied it to the directory on initial startup, so that MLKit could be used offline without an internet connection.
